const discount = [
	{
		id: "1",
		preOrder: false,
		canRead: false,
		productTitle: "এই নগরে হিমু",
		image: "/home/discount/ds(1).jpg",
		offer: 20,
		brand: "Brand 1",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "2",
		preOrder: false,
		canRead: false,
		productTitle: "এক ডজন কিশোর উপন্যাসসমগ্র",
		image: "/home/discount/ds(2).jpg",
		offer: 20,
		brand: "Brand 2",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "3",
		preOrder: false,
		canRead: false,
		productTitle: "এক ডজন সায়েন্স ফিকশন সমগ্র",
		image: "/home/discount/ds(3).jpg",
		offer: 20,
		brand: "Brand 3",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "4",
		preOrder: false,
		canRead: false,
		productTitle: "এক ডজন উপন্যাসসমগ্র",
		image: "/home/discount/ds(4).jpg",
		offer: 20,
		brand: "Brand 4",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "5",
		preOrder: false,
		canRead: false,
		productTitle: "একটি মামদো ভূতের গল্প",
		image: "/home/discount/ds(5).jpg",
		offer: 20,
		brand: "Brand 5",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "6",
		preOrder: false,
		canRead: false,
		productTitle: "উপন্যাসসমগ্র",
		image: "/home/discount/ds(6).jpg",
		offer: 20,
		brand: "Brand 6",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "7",
		preOrder: false,
		canRead: false,
		productTitle: "এবং হিমুচরিত",
		image: "/home/discount/ds(7).jpg",
		offer: 20,
		brand: "Brand 7",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "8",
		preOrder: false,
		canRead: false,
		productTitle: "যুগলবন্দি আজ হিমু ও চিত্রার বিয়ে",
		image: "/home/discount/ds(8).jpg",
		offer: 20,
		brand: "Brand 8",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "9",
		preOrder: false,
		canRead: false,
		productTitle: "নির্বাচিত অতিপ্রাকৃত গল্প",
		image: "/home/discount/ds(9).jpg",
		offer: 20,
		brand: "Brand 9",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "10",
		preOrder: false,
		canRead: false,
		productTitle: "অঁহক",
		image: "/home/discount/ds(10).jpg",
		offer: 20,
		brand: "Brand 10",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "11",
		preOrder: false,
		canRead: false,
		productTitle: "প্রথম ১",
		image: "/home/discount/ds(11).jpg",
		offer: 20,
		brand: "Brand 11",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "12",
		preOrder: false,
		canRead: false,
		productTitle: "হুমায়ূন আহমেদ রচনাবলী",
		image: "/home/discount/ds(12).jpg",
		offer: 20,
		brand: "Brand 12",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "13",
		preOrder: false,
		canRead: false,
		productTitle: "সানাউল্লার মহাবিপদ",
		image: "/home/discount/ds(13).jpg",
		offer: 20,
		brand: "Brand 13",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "14",
		preOrder: false,
		canRead: false,
		productTitle: "উপন্যাসসমগ্র",
		image: "/home/discount/ds(14).jpg",
		offer: 20,
		brand: "Brand 14",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "15",
		preOrder: false,
		canRead: false,
		productTitle: "উপন্যাসসমগ্র",
		image: "/home/discount/ds(15).jpg",
		offer: 20,
		brand: "Brand 15",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "16",
		preOrder: false,
		canRead: false,
		productTitle: "উপন্যাসসমগ্র",
		image: "/home/discount/ds(16).jpg",
		offer: 20,
		brand: "Brand 16",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "17",
		preOrder: false,
		canRead: false,
		productTitle: "উপন্যাসসমগ্র",
		image: "/home/discount/ds(17).jpg",
		offer: 20,
		brand: "Brand 17",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "18",
		preOrder: false,
		canRead: false,
		productTitle: "উপন্যাসসমগ্র",
		image: "/home/discount/ds(18).jpg",
		offer: 20,
		brand: "Brand 18",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "19",
		preOrder: false,
		canRead: false,
		productTitle: "রচনাবলী",
		image: "/home/discount/ds(19).jpg",
		offer: 20,
		brand: "Brand 19",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "20",
		preOrder: false,
		canRead: false,
		productTitle: "উপন্যাসসমগ্র",
		image: "/home/discount/ds(20).jpg",
		offer: 20,
		brand: "Brand 20",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "21",
		preOrder: false,
		canRead: false,
		productTitle: "মিসির আলি",
		image: "/home/discount/ds(21).jpg",
		offer: 20,
		brand: "Brand 21",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "22",
		preOrder: false,
		canRead: false,
		productTitle: "উপন্যাসসমগ্র",
		image: "/home/discount/ds(22).jpg",
		offer: 20,
		brand: "Brand 22",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "23",
		preOrder: false,
		canRead: false,
		productTitle: "আকাশ-পরী",
		image: "/home/discount/ds(23).jpg",
		offer: 20,
		brand: "Brand 23",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "24",
		preOrder: false,
		canRead: false,
		productTitle: "অমৃতসার",
		image: "/home/discount/ds(24).jpg",
		offer: 20,
		brand: "Brand 24",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "25",
		preOrder: false,
		canRead: false,
		productTitle: "আশ্চর্য মেঘদল",
		image: "/home/discount/ds(25).jpg",
		offer: 20,
		brand: "Brand 25",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "26",
		preOrder: false,
		canRead: false,
		productTitle: "বেলা অবেলা",
		image: "/home/discount/ds(26).jpg",
		offer: 20,
		brand: "Brand 26",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "27",
		preOrder: false,
		canRead: false,
		productTitle: "রুপোলি পর্দা",
		image: "/home/discount/ds(27).jpg",
		offer: 20,
		brand: "Brand 27",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "28",
		preOrder: false,
		canRead: false,
		productTitle: "অপেক্ষা",
		image: "/home/discount/ds(28).jpg",
		offer: 20,
		brand: "Brand 28",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "29",
		preOrder: false,
		canRead: false,
		productTitle: "রূপা",
		image: "/home/discount/ds(29).jpg",
		offer: 20,
		brand: "Brand 29",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
];

export default discount;
