const electronics = [
	{
		id: "1",
		preOrder: false,
		canRead: false,
		productTitle: "এই নগরে হিমু",
		image: "/home/discount/ds(1).jpg",
		offer: 20,
		brand: "Brand 1",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "2",
		preOrder: false,
		canRead: false,
		productTitle: "এক ডজন কিশোর উপন্যাসসমগ্র",
		image: "/home/discount/ds(2).jpg",
		offer: 20,
		brand: "Brand 2",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "3",
		preOrder: false,
		canRead: false,
		productTitle: "এক ডজন সায়েন্স ফিকশন সমগ্র",
		image: "/home/discount/ds(3).jpg",
		offer: 20,
		brand: "Brand 3",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "4",
		preOrder: false,
		canRead: false,
		productTitle: "এক ডজন উপন্যাসসমগ্র",
		image: "/home/discount/ds(4).jpg",
		offer: 20,
		brand: "Brand 4",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "5",
		preOrder: false,
		canRead: false,
		productTitle: "একটি মামদো ভূতের গল্প",
		image: "/home/discount/ds(5).jpg",
		offer: 20,
		brand: "Brand 5",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
];

export default electronics;
