const inStock = [
	{
		id: "1",
		preOrder: false,
		canRead: false,
		productTitle: "Elon Musk",
		image: "/Home/english-books/eb1.jpg",
		offer: 20,
		brand: "Walter Isaacson",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "2",
		preOrder: false,
		canRead: false,
		productTitle: "Eleven Minutes",
		image: "/Home/english-books/eb2.jpg",
		writer: "Paulo Coelho",
		review: {
			rating: 5,
			count: 150,
		},
		stock: 30,
		price: 120,
	},
	{
		id: "3",
		preOrder: false,
		canRead: false,
		productTitle: "The Little Prince",
		image: "/Home/english-books/eb3.jpg",
		offer: 10,
		writer: "Author 3",
		review: {
			rating: 3,
			count: 200,
		},
		stock: 0,
		price: 90,
		offerPrice: 81,
	},
	{
		id: "4",
		preOrder: false,
		canRead: false,
		productTitle: "Percy Jackson",
		image: "/Home/english-books/eb4.jpg",
		offer: 0,
		writer: "Rick Riodan",
		review: {
			rating: 4.5,
			count: 250,
		},
		stock: 10,
		price: 150,
		offerPrice: 112.5,
	},
	{
		id: "5",
		preOrder: false,
		canRead: false,
		productTitle: "Babu Bangladesh",
		image: "/Home/english-books/eb5.jpg",
		offer: 5,
		writer: "Numair Atif Choudhury",
		review: {
			rating: 4,
			count: 300,
		},
		stock: 60,
		price: 110,
		offerPrice: 104.5,
	},
	{
		id: "6",
		preOrder: false,
		canRead: false,
		productTitle: "Life Without Limits",
		image: "/Home/english-books/eb6.jpg",
		offer: 6,
		writer: "Nick Vujici",
		review: {
			rating: 4,
			count: 300,
		},
		stock: 60,
		price: 110,
		offerPrice: 104.5,
	},
	{
		id: "7",
		preOrder: false,
		canRead: false,
		productTitle: "Who Moved My Cheese?",
		image: "/Home/english-books/eb7.jpg",
		offer: 7,
		writer: "Dr Spencer Johnson",
		review: {
			rating: 4,
			count: 300,
		},
		stock: 0,
		price: 110,
		offerPrice: 104.5,
	},
	{
		id: "8",
		preOrder: false,
		canRead: false,
		productTitle: "My First Quran",
		image: "/Home/english-books/eb8.jpg",
		offer: 8,
		writer: "Saniyasnain Khan",
		review: {
			rating: 4,
			count: 300,
		},
		stock: 60,
		price: 110,
	},
	{
		id: "9",
		preOrder: false,
		canRead: false,
		productTitle: "48 Laws of Power",
		image: "/Home/english-books/eb9.jpg",
		offer: 0,
		writer: "Robert Greene",
		review: {
			rating: 4,
			count: 300,
		},
		stock: 60,
		price: 110,
		offerPrice: 104.9,
	},
	{
		id: "10",
		preOrder: false,
		canRead: false,
		productTitle: "Roots",
		image: "/Home/english-books/eb10.jpg",
		offer: 10,
		writer: "Vintage Haley",
		review: {
			rating: 4,
			count: 300,
		},
		stock: 60,
		price: 110,
		offerPrice: 104.5,
	},
	{
		id: "11",
		preOrder: false,
		canRead: false,
		productTitle: "The 4-Hour Work Week",
		image: "/Home/english-books/eb11.jpg",
		offer: 11,
		writer: "Tim Ferriss",
		review: {
			rating: 4,
			count: 300,
		},
		stock: 60,
		price: 110,
		offerPrice: 104.5,
	},
	{
		id: "12",
		preOrder: false,
		canRead: false,
		productTitle: "Adolf Hitler",
		image: "/Home/english-books/eb12.jpg",
		offer: 12,
		writer: "Mein Kampf",
		review: {
			rating: 4,
			count: 300,
		},
		stock: 60,
		price: 110,
		offerPrice: 104.12,
	},
	{
		id: "13",
		preOrder: false,
		canRead: false,
		productTitle: "Animal Farm",
		image: "/Home/english-books/eb13.jpg",
		offer: 13,
		writer: "George Orwell",
		review: {
			rating: 4,
			count: 300,
		},
		stock: 60,
		price: 110,
		offerPrice: 104.13,
	},
	{
		id: "14",
		preOrder: false,
		canRead: false,
		productTitle: "Relativity",
		image: "/Home/english-books/eb14.jpg",
		offer: 14,
		writer: "Albert Einstein",
		review: {
			rating: 4,
			count: 300,
		},
		stock: 0,
		price: 110,
	},
	{
		id: "15",
		preOrder: false,
		canRead: false,
		productTitle: "Ikigai",
		image: "/Home/english-books/eb15.jpg",
		offer: 15,
		writer: "Author 15",
		review: {
			rating: 4,
			count: 300,
		},
		stock: 60,
		price: 110,
		offerPrice: 104.15,
	},
	{
		id: "16",
		preOrder: false,
		canRead: false,
		productTitle: "Abraham Lincoln",
		image: "/Home/english-books/eb16.jpg",
		offer: 16,
		writer: "Lord Charenwood",
		review: {
			rating: 4,
			count: 300,
		},
		stock: 60,
		price: 110,
		offerPrice: 104.16,
	},
	{
		id: "17",
		preOrder: false,
		canRead: false,
		productTitle: "The Fountainhead",
		image: "/Home/english-books/eb17.jpg",
		offer: 17,
		writer: "Ayn Rand",
		review: {
			rating: 4,
			count: 310,
		},
		stock: 70,
		price: 120,
		offerPrice: 111.6,
	},
	{
		id: "18",
		preOrder: false,
		canRead: false,
		productTitle: "Do Epic Shit",
		image: "/Home/english-books/eb18.jpg",
		offer: 18,
		writer: "Ankur Warikoo",
		review: {
			rating: 4,
			count: 320,
		},
		stock: 80,
		price: 130,
		offerPrice: 118.4,
	},
	{
		id: "19",
		preOrder: false,
		canRead: false,
		productTitle: "A Tale of Two Cities",
		image: "/Home/english-books/eb19.jpg",
		offer: 19,
		writer: "Charles Dickens",
		review: {
			rating: 4,
			count: 330,
		},
		stock: 90,
		price: 140,
		offerPrice: 125.4,
	},
	{
		id: "20",
		preOrder: false,
		canRead: false,
		productTitle: "The Gut",
		image: "/Home/english-books/eb20.jpg",
		offer: 20,
		writer: "Payal Kothari",
		review: {
			rating: 4,
			count: 340,
		},
		stock: 100,
		price: 150,
		offerPrice: 132.5,
	},
	{
		id: "21",
		preOrder: false,
		canRead: false,
		productTitle: "Life's Amazing Secrets",
		image: "/Home/english-books/eb21.jpg",
		offer: 21,
		writer: "Gaur Gopal Das",
		review: {
			rating: 4,
			count: 350,
		},
		stock: 110,
		price: 160,
		offerPrice: 139.6,
	},
	{
		id: "22",
		preOrder: false,
		canRead: false,
		productTitle: "The Laws of Human Nature",
		image: "/Home/english-books/eb22.jpg",
		offer: 22,
		writer: "Robert Greene",
		review: {
			rating: 4,
			count: 360,
		},
		stock: 120,
		price: 170,
		offerPrice: 146.8,
	},
	{
		id: "23",
		preOrder: false,
		canRead: false,
		productTitle: "Applied English Grammar and Composition",
		image: "/Home/english-books/eb23.jpg",
		offer: 23,
		writer: "p e das",
		review: {
			rating: 4,
			count: 370,
		},
		stock: 130,
		price: 180,
		offerPrice: 154,
	},
	{
		id: "24",
		preOrder: false,
		canRead: false,
		productTitle: "The Intelligent Investor",
		image: "/Home/english-books/eb24.jpg",
		offer: 24,
		writer: "Benjiamin Graham",
		review: {
			rating: 4,
			count: 380,
		},
		stock: 140,
		price: 190,
		offerPrice: 161.2,
	},
	{
		id: "25",
		preOrder: false,
		canRead: false,
		productTitle: "Akbar & Birbal",
		image: "/Home/english-books/eb25.jpg",
		offer: 25,
		writer: "Author 25",
		review: {
			rating: 4,
			count: 390,
		},
		stock: 150,
		price: 200,
		offerPrice: 168.5,
	},
	{
		id: "26",
		preOrder: false,
		canRead: false,
		productTitle: "The Quran",
		image: "/Home/english-books/eb26.jpg",
		offer: 26,
		writer: "M A S Abdel Haleem",
		review: {
			rating: 4,
			count: 400,
		},
		stock: 160,
		price: 210,
		offerPrice: 175.8,
	},
	{
		id: "27",
		preOrder: false,
		canRead: false,
		productTitle: "The Lost Symbol",
		image: "/Home/english-books/eb27.jpg",
		offer: 27,
		writer: "Dan Brown",
		review: {
			rating: 4,
			count: 410,
		},
		stock: 170,
		price: 220,
		offerPrice: 183.1,
	},
	{
		id: "28",
		preOrder: false,
		canRead: false,
		productTitle: "Rich Dad Poor Dad",
		image: "/Home/english-books/eb28.jpg",
		offer: 28,
		writer: "Robert Kiyosaki",
		review: {
			rating: 4,
			count: 420,
		},
		stock: 180,
		price: 230,
		offerPrice: 190.4,
	},
	{
		id: "29",
		preOrder: false,
		canRead: false,
		productTitle: "Think and Grow Rich",
		image: "/Home/english-books/eb29.jpg",
		offer: 29,
		writer: "Napoleon Hill",
		review: {
			rating: 4,
			count: 430,
		},
		stock: 190,
		price: 240,
		offerPrice: 197.7,
	},
	{
		id: "30",
		preOrder: false,
		canRead: false,
		productTitle: "Inferno",
		image: "/Home/english-books/eb30.jpg",
		offer: 30,
		writer: "Dan Brown",
		review: {
			rating: 4,
			count: 440,
		},
		stock: 200,
		price: 250,
		offerPrice: 205,
	},
];

export default inStock;
