const others = [
	{
		id: "1",
		preOrder: false,
		canRead: false,
		productTitle: "লং ওয়াক টু ফ্রিডম",
		image: "/home/others/others(1).jpg",
		offer: 20,
		brand: "Brand 1",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "2",
		preOrder: false,
		canRead: false,
		productTitle: "নির্বাসন",
		image: "/home/others/others(2).jpg",
		offer: 20,
		brand: "Brand 2",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "3",
		preOrder: false,
		canRead: false,
		productTitle: "তোমাকে দেখার অসুখ",
		image: "/home/others/others(3).jpg",
		offer: 20,
		brand: "Brand 3",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "4",
		preOrder: false,
		canRead: false,
		productTitle: "সিক্রেট মিশনস: মোসাদ স্টোরিজ",
		image: "/home/others/others(4).jpg",
		offer: 20,
		brand: "Brand 4",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "5",
		preOrder: false,
		canRead: false,
		productTitle: "বিন্দু বৃত্তান্তে",
		image: "/home/others/others(5).jpg",
		offer: 20,
		brand: "Brand 5",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "6",
		preOrder: false,
		canRead: false,
		productTitle: "দ্য আর্চার",
		image: "/home/others/others(6).jpg",
		offer: 20,
		brand: "Brand 6",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "7",
		preOrder: false,
		canRead: false,
		productTitle: "পোটকরা টু ম্যানহাটন",
		image: "/home/others/others(7).jpg",
		offer: 20,
		brand: "Brand 7",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "8",
		preOrder: false,
		canRead: false,
		productTitle: "ছদ্মবেশ",
		image: "/home/others/others(8).jpg",
		offer: 20,
		brand: "Brand 8",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "9",
		preOrder: false,
		canRead: false,
		productTitle: "মাকতুব",
		image: "/home/others/others(9).jpg",
		offer: 20,
		brand: "Brand 9",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "10",
		preOrder: false,
		canRead: false,
		productTitle: "এক টুকরো মেঘ",
		image: "/home/others/others(10).jpg",
		offer: 20,
		brand: "Brand 10",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "11",
		preOrder: false,
		canRead: false,
		productTitle: "আরশিনগর",
		image: "/home/others/others(11).jpg",
		offer: 20,
		brand: "Brand 11",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "12",
		preOrder: false,
		canRead: false,
		productTitle: "শেষ অধ্যায় নেই",
		image: "/home/others/others(12).jpg",
		offer: 20,
		brand: "Brand 12",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "13",
		preOrder: false,
		canRead: false,
		productTitle: "ঘুরে দাঁড়াও আরেকবার",
		image: "/home/others/others(13).jpg",
		offer: 20,
		brand: "Brand 13",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "14",
		preOrder: false,
		canRead: false,
		productTitle: "কী করিলে বলো পাইবো তোমারে",
		image: "/home/others/others(14).jpg",
		offer: 20,
		brand: "Brand 14",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "15",
		preOrder: false,
		canRead: false,
		productTitle: "লিডারশিপ ১০১",
		image: "/home/others/others(15).jpg",
		offer: 20,
		brand: "Brand 15",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "16",
		preOrder: false,
		canRead: false,
		productTitle: "মার্কেটিং",
		image: "/home/others/others(16).jpg",
		offer: 20,
		brand: "Brand 16",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "17",
		preOrder: false,
		canRead: false,
		productTitle: "মায়ামৃগ",
		image: "/home/others/others(17).jpg",
		offer: 20,
		brand: "Brand 17",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "18",
		preOrder: false,
		canRead: false,
		productTitle: "মক্কা মদিনা জেরুজালেম",
		image: "/home/others/others(18).jpg",
		offer: 20,
		brand: "Brand 18",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "19",
		preOrder: false,
		canRead: false,
		productTitle: "প্রতিশোধ",
		image: "/home/others/others(19).jpg",
		offer: 20,
		brand: "Brand 19",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "20",
		preOrder: false,
		canRead: false,
		productTitle: "রিলেশনশিপস ১০১",
		image: "/home/others/others(20).jpg",
		offer: 20,
		brand: "Brand 20",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "21",
		preOrder: false,
		canRead: false,
		productTitle: "সে এসে বসুক পাশে",
		image: "/home/others/others(21).jpg",
		offer: 20,
		brand: "Brand 21",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "22",
		preOrder: false,
		canRead: false,
		productTitle: "সিপাহী",
		image: "/home/others/others(22).jpg",
		offer: 20,
		brand: "Brand 22",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "23",
		preOrder: false,
		canRead: false,
		productTitle: "সত্যটা মিথ্যা",
		image: "/home/others/others(23).jpg",
		offer: 20,
		brand: "Brand 23",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "24",
		preOrder: false,
		canRead: false,
		productTitle: "Product Title 24",
		image: "/home/others/others(24).jpg",
		offer: 20,
		brand: "Brand 24",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "25",
		preOrder: false,
		canRead: false,
		productTitle: "তোমার জন্য দাঁড়িয়ে ছিলাম বলে",
		image: "/home/others/others(25).jpg",
		offer: 20,
		brand: "Brand 25",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "26",
		preOrder: false,
		canRead: false,
		productTitle: "উইংস অব ফায়ার",
		image: "/home/others/others(26).jpg",
		offer: 20,
		brand: "Brand 26",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "27",
		preOrder: false,
		canRead: false,
		productTitle: "লিডারশিপ",
		image: "/home/others/others(27).jpg",
		offer: 20,
		brand: "Brand 27",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "28",
		preOrder: false,
		canRead: false,
		productTitle: "Product Title 28",
		image: "/home/others/others(28).jpg",
		offer: 20,
		brand: "Brand 28",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
	{
		id: "29",
		preOrder: false,
		canRead: false,
		productTitle: "Product Title 29",
		image: "/home/others/others(29).jpg",
		offer: 20,
		brand: "Brand 29",
		review: {
			rating: 4,
			count: 100,
		},
		stock: 0,
		price: 100,
	},
];

export default others;
